import {test,expect} from '@playwright/test';
import {mock,status,showFeed,setup} from './display-fixture';

test('PC setup separates preparing a plan, reviewing it, applying and enabling capture',async({page})=>{
  const initial=status();initial.enabled=false;initial.status='Setup required';initial.setup.can_apply=true;initial.setup.can_restore=true;initial.setup.dcs_running=false;const control=await mock(page,initial);await page.evaluate(()=>{(window as any).__feedSnapshot.health.dcs_running=false;});await setup(page);await page.getByLabel('Dedicated export monitor').selectOption('exports');expect(control.writes).toEqual([]);await page.getByRole('button',{name:'Prepare display layout',exact:true}).click();await expect(page.getByRole('region',{name:'Display layout review'})).toBeVisible();expect(control.writes).toEqual([{path:'/api/display-feed/plan',body:{monitor_id:'exports'}}]);await expect(page.getByRole('button',{name:'Apply reviewed layout',exact:true})).toBeDisabled();await page.getByRole('checkbox',{name:'I reviewed the layout',exact:false}).check();await page.getByRole('button',{name:'Apply reviewed layout',exact:true}).click();expect(control.writes.at(-1)).toEqual({path:'/api/display-feed/apply',body:{plan_id:'plan-one'}});expect(control.writes.some(row=>row.path.endsWith('/enabled'))).toBe(false);await expect(page.getByRole('button',{name:'Enable display capture',exact:true})).toBeDisabled();control.feed.status='Disabled';control.feed.setup.status='active';await page.getByRole('button',{name:'Refresh display setup',exact:true}).click();await page.getByRole('button',{name:'Enable display capture',exact:true}).click();expect(control.writes.at(-1)).toEqual({path:'/api/display-feed/enabled',body:{enabled:true}});
});

test('running DCS blocks Apply and Restore; phone setup cannot submit PC changes',async({page})=>{
  const initial=status();initial.setup.can_apply=true;initial.setup.can_restore=true;const control=await mock(page,initial);await setup(page);await page.getByLabel('Dedicated export monitor').selectOption('exports');await page.getByRole('button',{name:'Prepare display layout',exact:true}).click();await page.getByRole('checkbox',{name:'I reviewed the layout',exact:false}).check();await expect(page.getByRole('button',{name:'Apply reviewed layout',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Restore previous display layout',exact:true})).toBeDisabled();control.feed.can_edit=false;await page.getByRole('button',{name:'Refresh display setup',exact:true}).click();await expect(page.locator('.display-feed-pc-note')).toBeVisible();await expect(page.getByRole('button',{name:'Prepare display layout',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Enable display capture',exact:true})).toHaveCount(0);expect(control.writes).toHaveLength(1);
});

test('unavailable image service leaves the existing exported text switch usable',async({page})=>{
  await page.setViewportSize({width:390,height:844});const control=await mock(page);await page.route('**/api/display-feed',route=>route.fulfill({status:404,json:{detail:'Not installed'}}));await setup(page);await page.getByRole('button',{name:'Refresh display setup',exact:true}).click();const feed=await showFeed(page);await expect(feed.getByRole('button',{name:'Text',exact:true})).toHaveAttribute('aria-pressed','true');await feed.getByRole('button',{name:'Live stream',exact:true}).click();await expect(feed).toContainText('service unavailable');await feed.getByRole('button',{name:'Text',exact:true}).click();await expect(page.getByText('EXPORTED TEXT FALLBACK',{exact:true})).toBeVisible();expect(control.writes).toEqual([]);
});




test('unavailable monitor layouts cannot prepare or enable capture',async({page})=>{
  const initial=status();initial.enabled=false;initial.status='Setup required';initial.setup.status='unavailable';initial.setup.can_plan=false;initial.setup.eligible_monitor_ids=[];initial.setup.detail='The secondary display must sit immediately to the right of the primary display.';const control=await mock(page,initial);await setup(page);await expect(page.getByRole('button',{name:'Prepare display layout',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Enable display capture',exact:true})).toBeDisabled();await expect(page.locator('.display-feed-setup')).toContainText('immediately to the right');expect(control.writes).toEqual([]);
});


test('capture off defaults to current exported text and automatic image mode follows capture availability',async({page})=>{
  await page.setViewportSize({width:390,height:844});const initial=status();initial.enabled=false;initial.status='Disabled';const control=await mock(page,initial);let feed=await showFeed(page);await expect(feed.getByRole('button',{name:'Text',exact:true})).toHaveAttribute('aria-pressed','true');await expect(feed).toContainText('EXPORTED TEXT FALLBACK');expect(control.frames).toEqual([]);
  control.feed.enabled=true;control.feed.status='Ready';await setup(page);await page.getByRole('button',{name:'Refresh display setup',exact:true}).click();feed=await showFeed(page);await expect(feed.getByRole('button',{name:'Live stream',exact:true})).toHaveAttribute('aria-pressed','true');await expect(feed.getByRole('img')).toBeVisible();
  control.feed.enabled=false;control.feed.status='Disabled';await page.getByRole('button',{name:'Refresh display setup',exact:true}).click();feed=await showFeed(page);await expect(feed.getByRole('button',{name:'Text',exact:true})).toHaveAttribute('aria-pressed','true');await expect(feed).toContainText('EXPORTED TEXT FALLBACK');await expect(feed.getByRole('img')).toHaveCount(0);expect(control.writes).toEqual([]);
});

test('explicit display source survives capture changes and manual image mode explains why capture is off',async({page})=>{
  await page.setViewportSize({width:390,height:844});const initial=status();initial.enabled=false;initial.status='Disabled';const control=await mock(page,initial);let feed=await showFeed(page);await feed.getByRole('button',{name:'Live stream',exact:true}).click();await expect(feed).toContainText('Capture is off');expect(control.frames).toEqual([]);await feed.getByRole('button',{name:'Text',exact:true}).click();
  control.feed.enabled=true;control.feed.status='Ready';await setup(page);await page.getByRole('button',{name:'Refresh display setup',exact:true}).click();feed=await showFeed(page);await expect(feed.getByRole('button',{name:'Text',exact:true})).toHaveAttribute('aria-pressed','true');await expect(feed).toContainText('EXPORTED TEXT FALLBACK');expect(control.frames).toEqual([]);
  await feed.getByRole('button',{name:'Live stream',exact:true}).click();await expect(feed.getByRole('img')).toBeVisible();control.feed.enabled=false;control.feed.status='Disabled';await page.getByRole('button',{name:'Refresh display setup',exact:true}).click();feed=await showFeed(page);await expect(feed.getByRole('button',{name:'Live stream',exact:true})).toHaveAttribute('aria-pressed','true');await expect(feed).toContainText('Capture is off');await expect(feed.getByRole('img')).toHaveCount(0);expect(control.writes).toEqual([]);
});


function virtualStatus(){const initial=status();initial.enabled=false;initial.status='Setup required';initial.setup.status='not-configured';initial.setup.can_plan=true;initial.setup.can_apply=true;initial.setup.dcs_running=false;initial.setup.monitors.push({id:'virtual',name:'Virtual export display',kind:'virtual',adapter_description:'Verified virtual display adapter',primary:false,x:1920,y:1080,width:1536,height:512});initial.setup.eligible_monitor_ids=['exports','virtual'];initial.setup.recommended_monitor_id='virtual';return initial;}
for(const viewport of [{width:390,height:844},{width:1180,height:820}])test(`virtual export review preserves physical monitor wording at ${viewport.width}px without automatic writes`,async({page})=>{
  await page.setViewportSize(viewport);const control=await mock(page,virtualStatus());await page.evaluate(()=>{(window as any).__feedSnapshot.health.dcs_running=false;});await setup(page);await expect(page.getByLabel('Dedicated export monitor')).toHaveValue('virtual');await expect(page.getByRole('button',{name:'Prepare display layout',exact:true})).toBeEnabled();expect(control.writes).toEqual([]);await page.getByRole('button',{name:'Prepare display layout',exact:true}).click();const review=page.getByRole('region',{name:'Display layout review'});await expect(review).toContainText('Your physical monitors remain available for other apps.');await expect(review).not.toContainText('entire selected monitor');await expect(review.getByRole('checkbox')).toHaveAccessibleName('I reviewed the layout and will use the virtual display for DCS exports.');await expect(page.getByRole('button',{name:'Apply reviewed layout',exact:true})).toBeDisabled();expect(control.writes).toEqual([{path:'/api/display-feed/plan',body:{monitor_id:'virtual'}}]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await review.screenshot({path:`test-results/display-feed/virtual-review-${viewport.width}.png`});
});

test('no virtual display defaults to no selection; a physical monitor requires an explicit choice and warning',async({page})=>{
  const initial=status();initial.enabled=false;initial.status='Setup required';initial.setup.status='not-configured';const control=await mock(page,initial);await setup(page);await expect(page.getByLabel('Dedicated export monitor')).toHaveValue('');await expect(page.getByRole('button',{name:'Prepare display layout',exact:true})).toBeDisabled();await expect(page.locator('.display-feed-virtual-help')).toContainText('No virtual display is detected');await expect(page.locator('.display-feed-virtual-help')).toContainText('does not install drivers');await page.getByLabel('Dedicated export monitor').selectOption('exports');await expect(page.locator('.display-feed-choice')).toContainText('other apps cannot remain visible');expect(control.writes).toEqual([]);await page.getByRole('button',{name:'Prepare display layout',exact:true}).click();await expect(page.getByRole('region',{name:'Display layout review'})).toContainText('entire selected monitor');await expect(page.getByRole('region',{name:'Display layout review'})).not.toContainText('Your physical monitors remain available');
});

test('unknown display types and unverified virtual plans never claim physical monitors are preserved',async({page})=>{
  const initial=virtualStatus();delete initial.setup.monitors[2].kind;initial.setup.monitors[2].name='Virtual Display Driver (name alone is not proof)';const control=await mock(page,initial);await setup(page);await expect(page.getByLabel('Dedicated export monitor')).toHaveValue('');await page.getByLabel('Dedicated export monitor').selectOption('virtual');await expect(page.locator('.display-feed-choice')).toContainText('Display type is unknown');await page.getByRole('button',{name:'Prepare display layout',exact:true}).click();const review=page.getByRole('region',{name:'Display layout review'});await expect(review).not.toContainText('Your physical monitors remain available');control.feed.setup.plan!.export_kind='virtual';control.feed.setup.plan!.physical_monitors_preserved=false;await page.getByRole('button',{name:'Refresh display setup',exact:true}).click();await expect(review).toContainText('has not yet verified');await expect(review).not.toContainText('Your physical monitors remain available');
});

test('changing the selected display invalidates approval of an older plan without writing settings',async({page})=>{
  const control=await mock(page,virtualStatus());await page.evaluate(()=>{(window as any).__feedSnapshot.health.dcs_running=false;});await setup(page);await page.getByRole('button',{name:'Prepare display layout',exact:true}).click();await page.getByRole('checkbox',{name:'I reviewed the layout',exact:false}).check();await expect(page.getByRole('button',{name:'Apply reviewed layout',exact:true})).toBeEnabled();await page.getByLabel('Dedicated export monitor').selectOption('exports');await expect(page.getByRole('button',{name:'Apply reviewed layout',exact:true})).toBeDisabled();await expect(page.getByRole('checkbox',{name:'I reviewed the layout',exact:false})).toBeDisabled();await expect(page.getByRole('region',{name:'Display layout review'})).toContainText('Prepare a new layout');expect(control.writes).toHaveLength(1);
});


test('unconfigured production status with unknown export kind still offers virtual-driver guidance',async({page})=>{
  const initial=status();initial.enabled=false;initial.status='Setup required';initial.revision='';initial.setup.status='not-configured';initial.setup.export_kind='unknown';initial.setup.physical_monitors_preserved=false;initial.setup.recommended_monitor_id=null;initial.setup.monitor_id=null;const control=await mock(page,initial);await setup(page);await expect(page.getByLabel('Dedicated export monitor')).toHaveValue('');await expect(page.locator('.display-feed-virtual-help')).toContainText('No virtual display is detected');await expect(page.locator('.display-feed-choice')).toHaveCount(0);await expect(page.getByRole('button',{name:'Prepare display layout',exact:true})).toBeDisabled();expect(control.writes).toEqual([]);
});
