import { createPortal } from 'react-dom';
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { request, useSnapshot } from './api';
import { useDisplayPreference, VIEWS } from './preferences';
import NavigationScope, { Badge, Metric } from './Scope';
import Sensors from './Sensors';
import Cockpit from './Cockpit';
import Controls from './Controls';
import Remote from './Remote';
import './workspace.css';
import FlightData from './FlightData';
import Appearance from './Appearance';
import Setup from './Setup';
import PairDevice from './PairDevice';
import ConnectionHealth from './ConnectionHealth';
import { awarenessView } from './MissionAwareness';
import { aircraftPalette } from './themes';
import type { Palette } from './themes';
import type { GuideAction, Snapshot } from './types';
import { age, bindingText, coords, format, list, number, obj, text, uuid } from './utils';

const views = VIEWS;
const terminalStates = ['Idle','Confirmed','Unconfirmed','Rejected','Expired','Cancelled'];

function QueueCard({ snapshot, cancel, busy, connected }: {snapshot?: Snapshot; cancel:()=>void; busy:boolean; connected:boolean}) {
  const q=snapshot?.queue, state=q?.state??'Idle', active=!terminalStates.includes(state);
  return <section className="panel queue-card"><div className="panel-header"><span className="eyebrow">COMMAND QUEUE · ONE ACTION</span><Badge tone={state==='Confirmed'?'green':active?'amber':''}>{state}</Badge></div><div className="queue-progress">{['Selected','Queued','Awaiting DCS Focus','Settling','Revalidating','Sent','Confirming'].map(s=><span key={s} className={state===s?'current':''}>{s}</span>)}</div><h2>{q?.action_id ? text(q.action_id) : 'No action queued'}</h2><p>{q?.detail || 'Choose a guide action. Execution always passes through the existing guarded sender.'}</p><div className="queue-status"><span>REQUEST <code>{q?.request_id || '—'}</code></span><span>{snapshot?.server?.dry_run !== false ? 'DRY RUN · no input sent' : 'LIVE INPUT ENABLED'}</span></div>{active&&<button className="danger-button" disabled={busy||!connected} onClick={cancel}>Cancel queued action</button>}<details><summary>Recent transitions</summary><ol className="queue-history">{list(q?.history).map((h,i)=><li key={i}><strong>{text(h.state)}</strong> {text(h.detail??h.reason,'')}<small>{text(h.at??h.timestamp,'')}</small></li>)}</ol></details><p className="micro">“Sent” comes from the sender audit. “Confirmed” needs an observable aircraft state transition. Telemetry cannot identify who caused a change.</p></section>;
}

function Guide({ snapshot, usable }: {snapshot?:Snapshot;usable:boolean}) {
  const actions=snapshot?.guide?.actions??[];
  const [mode,setMode]=useState<'Observe'|'Assist'>('Observe'), [selected,setSelected]=useState(''), [review,setReview]=useState<GuideAction>(), [understood,setUnderstood]=useState(false), [busy,setBusy]=useState(false), [error,setError]=useState('');
  const action=actions.find(a=>a.id===selected)??actions[0];
  const active=!terminalStates.includes(snapshot?.queue?.state??'Idle');
  const reviewButton=useRef<HTMLButtonElement>(null), dialog=useRef<HTMLDialogElement>(null);
  const contextKey=JSON.stringify([snapshot?.health?.aircraft,snapshot?.health?.session,snapshot?.health?.mission,snapshot?.bindings?.source_fingerprint,snapshot?.bindings?.current_fingerprint,usable]);
  useEffect(()=>{setReview(undefined);setUnderstood(false);setMode('Observe');},[contextKey]);
  useEffect(()=>{ if(review) dialog.current?.showModal(); else dialog.current?.close(); },[review]);
  const closeReview=()=>{setReview(undefined);setUnderstood(false);reviewButton.current?.focus();};
  async function send() {
    if(!review||!understood||busy||!usable) return;
    setBusy(true);setError('');
    try { await request('/api/commands',{request_id:uuid(),action_id:review.id,confirmed:true});closeReview(); }
    catch(e){setError(e instanceof Error?e.message:'Request failed. Check the queue before trying again.');closeReview();}
    finally{setBusy(false);}
  }
  async function cancel() {if(!snapshot?.queue?.request_id)return;setBusy(true);try{await request(`/api/commands/${encodeURIComponent(snapshot.queue.request_id)}/cancel`,{});}catch(e){setError(e instanceof Error?e.message:'Cancellation failed');}finally{setBusy(false);}}
  return <div className="page-view"><div className="page-title"><div><span className="eyebrow">ONE STEP · OBSERVE, THEN ACT</span><h1>Aircraft guide<span className="title-period">.</span></h1><p>State-aware assistance for {text(snapshot?.health?.aircraft,'the active aircraft')}.</p></div><div className="segmented"><button aria-pressed={mode==='Observe'} onClick={()=>setMode('Observe')}>Observe</button><button aria-pressed={mode==='Assist'} onClick={()=>setMode('Assist')}>Assist</button><button disabled title="Automatic sequences are not available in the MVP">Sequence · unavailable</button></div></div>
    <div className="guide-layout"><aside className="panel guide-actions"><div className="panel-header"><span className="eyebrow">AVAILABLE GUIDE STEPS</span><Badge>{actions.length}</Badge></div>{actions.length ? actions.map((a,i)=><button key={a.id} className={`guide-action ${a.id===action?.id?'selected':''}`} onClick={()=>{setSelected(a.id);closeReview();}}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{a.title}</strong><small>{bindingText(a.binding)}</small></div><span>›</span></button>):<p className="empty-small">No verified actions available for the current aircraft.</p>}<div className="guide-mode-note"><strong>{mode} mode</strong><p>{mode==='Observe'?'Inspect the step and use your controls. No input is sent.':'Review one benign action, confirm deliberately, then let the guarded queue wait for DCS focus.'}</p></div></aside>
      <section className="panel guide-step"><div className="panel-header"><span className="eyebrow">CURRENT STEP</span><Badge tone="amber">{text(action?.risk,'No action')}</Badge></div><h2>{action?.title??'Waiting for an aircraft'}</h2><p className="guide-purpose">{action?.purpose??'The guide loads aircraft-specific controls after the aircraft and binding index are identified.'}</p><dl className="step-details"><div><dt>Observed state</dt><dd>{text(action?.observed_state??action?.current_observed_state,'Unknown / not observable')}</dd></div><div><dt>Required control</dt><dd><kbd>{bindingText(action?.binding)}</kbd></dd></div><div><dt>Cockpit or device location</dt><dd>{text(action?.location)}</dd></div><div><dt>Expected result</dt><dd>{text(action?.expected_result)}</dd></div><div><dt>Can the result be confirmed?</dt><dd>{action?.observable?'Aircraft-specific observation required':'No · Sent—state not observable'}</dd></div><div><dt>Completion</dt><dd>{snapshot?.queue?.action_id===action?.id ? snapshot?.queue?.state??'Not started':'Not started'}</dd></div></dl>
        {action?.is_toggle&&!action.observable&&<p className="notice amber">Toggle starting state is unknown. Its result is unconfirmable.</p>}{action?.reason&&<p className="notice">{action.reason}</p>}{snapshot?.health?.dcs_focused&&mode==='Assist'&&<p className="notice amber">DCS is already focused. A confirmed action may execute immediately after the focus settling checks.</p>}
        <button ref={reviewButton} className="primary-button" disabled={mode!=='Assist'||!action?.enabled||!usable||busy||active} onClick={()=>{if(action){setUnderstood(false);setReview(action);}}}>{mode==='Observe'?'Observe mode · input disabled':active?'One action already queued':'Review action →'}</button><p className="micro">{snapshot?.server?.dry_run!==false?'Dry run is enabled. The sender records an audit entry without sending input.':'Live input is enabled. Confirming can send this action to DCS.'}</p>
      </section><QueueCard snapshot={snapshot} cancel={()=>void cancel()} busy={busy} connected={usable}/></div>{error&&<p className="notice error" role="alert">{error}</p>}
    <dialog ref={dialog} onCancel={e=>{e.preventDefault();closeReview();}} className="confirm-dialog"><span className="eyebrow">DELIBERATE CONFIRMATION</span><h2>{review?.title}</h2><p>{snapshot?.health?.dcs_focused?'DCS is already focused. This action may execute as soon as focus settles and safety checks pass.':'After confirmation, return focus to DCS. This single action expires if the queue cannot safely send it.'}</p><div className="confirm-combo"><kbd>{bindingText(review?.binding)}</kbd><Badge tone={snapshot?.server?.dry_run!==false?'amber':'red'}>{snapshot?.server?.dry_run!==false?'DRY RUN':'LIVE INPUT'}</Badge></div><p>{review?.observable?'Confirmation requires an aircraft-specific observed result.':'The result is not observable. The queue must not claim the aircraft state is confirmed.'}</p><label className="confirmation-check"><input type="checkbox" checked={understood} onChange={e=>setUnderstood(e.target.checked)}/>I understand this queues one action{snapshot?.server?.dry_run===false?' and may send input to DCS':''}.</label><div className="dialog-buttons"><button className="plain-button" onClick={closeReview}>Go back</button><button className="primary-button" disabled={!understood||busy||!usable} onClick={()=>void send()}>{busy?'Submitting…':'Confirm and queue once'}</button></div></dialog>
  </div>;
}

function Health({ snapshot, connection, receivedAt, connectionPanel }: {snapshot?: Snapshot; connection:string;receivedAt:number;connectionPanel:React.ReactNode}) {
  const h=snapshot?.health, nav=obj(snapshot?.navigation), prov=obj(nav.provenance), bindings=obj(snapshot?.bindings);
  const mission=snapshot?.mission,missionCurrent=connection==='connected'&&mission?.status==='Current';
  const sources=list(prov.sources);
  const coverage=list(nav.coverage);
  const capabilities=obj(h?.export_capabilities);
  return <div className="page-view"><div className="page-title"><div><span className="eyebrow">INDEPENDENT FRESHNESS · EXPLICIT LIMITATIONS</span><h1>Data health<span className="title-period">.</span></h1><p>Know what is available before relying on it.</p></div><Badge tone={connection==='connected'?'green':'amber'}>{connection}</Badge></div>{connectionPanel}<div className="health-grid"><section className="panel health-card"><span className="eyebrow">DCS & SESSION</span><h2>{connection==='connected'?text(h?.status,'Unknown'):connection==='delayed'?'Updates delayed':connection==='reconnecting'?'Reconnecting':'Offline'}</h2><dl className="step-details"><div><dt>DCS process</dt><dd>{h?.dcs_running?'Running':'Not detected'}</dd></div><div><dt>DCS foreground</dt><dd>{h?.dcs_focused?'Yes':'No'}</dd></div><div><dt>Aircraft</dt><dd>{text(h?.aircraft)}</dd></div><div><dt>Terrain</dt><dd>{text(h?.terrain)}</dd></div><div><dt>Mission</dt><dd>{missionCurrent?text(mission?.name,'Unavailable'):'Unavailable'}</dd></div><div><dt>Session</dt><dd>{text(h?.session)}</dd></div></dl><details className="sensor-source"><summary>Mission source details</summary><p>{text(mission?.source,'Source unavailable')}</p><p>Status · {connection==='connected'?text(mission?.status,'Unavailable'):'Offline'}</p><p className="hash">Export identity · {text(h?.mission)}</p></details></section>
      <section className="panel health-card"><span className="eyebrow">TWO INDEPENDENT CLOCKS</span><h2>Telemetry & cockpit</h2><div className="freshness-row"><Metric label="OWNSHIP TELEMETRY AGE" value={age(h?.telemetry_age_s)}/><Badge tone={h?.telemetry_fresh&&connection==='connected'?'green':'amber'}>{h?.telemetry_fresh&&connection==='connected'?'Fresh':'Stale / unavailable'}</Badge></div><div className="freshness-row"><Metric label="COCKPIT DISPLAY AGE" value={age(h?.display_age_s)}/><Badge tone={h?.displays_fresh&&connection==='connected'?'green':'amber'}>{h?.displays_fresh&&connection==='connected'?'Fresh':'Stale / unavailable'}</Badge></div><p className="micro">Last dashboard update: {receivedAt?new Date(receivedAt).toLocaleTimeString():'Unknown'}. Fresh ownship does not imply fresh cockpit displays.</p></section>
      <section className="panel health-card"><span className="eyebrow">ACCESS & DELIVERY</span><h2>{snapshot?.server?.lan_enabled?'LAN control enabled':'Loopback access'}</h2><dl className="step-details"><div><dt>Execution</dt><dd>{snapshot?.server?.remote_armed?'Remote live enabled · Guide '+(snapshot.server.dry_run===false?'live':'preview'):snapshot?.server?.dry_run!==false?'Preview · no input':'Guide live enabled · Remote preview'}</dd></div><div><dt>Connected clients</dt><dd>{format(snapshot?.server?.connected_clients)}</dd></div><div><dt>Physical input</dt><dd>{text(h?.physical_input_status,'Unavailable')}</dd></div><div><dt>Sensor layer</dt><dd>{text(h?.sensor_status,'Unverified')}</dd></div><div><dt>Browser storage</dt><dd>App shell and display preferences only</dd></div></dl></section>
      <section className="panel health-card"><span className="eyebrow">BINDING SOURCE OF TRUTH</span><h2>{text(bindings.status??h?.binding_status,'Unavailable')}</h2><dl className="step-details"><div><dt>Aircraft index</dt><dd>{text(bindings.aircraft)}</dd></div><div><dt>Generated</dt><dd>{text(bindings.generated_utc??bindings.generated_at)}</dd></div><div><dt>Actions / devices</dt><dd>{list(bindings.actions).length} / {list(bindings.devices).length}</dd></div><div><dt>Source fingerprint</dt><dd className="hash">{text(bindings.source_fingerprint??bindings.source_hash)}</dd></div></dl><p className="micro">Module defaults + current user diffs. Bindings are never inherited from another aircraft. HTML snapshots are excluded.</p></section>
      <section className="panel health-card"><span className="eyebrow">NAVIGATION DATABASE</span><h2>{text(nav.status,'Unavailable')}</h2><dl className="step-details"><div><dt>DCS version</dt><dd>{text(prov.dcs_version??bindings.dcs_version)}</dd></div><div><dt>Schema version</dt><dd>{text(prov.schema_version)}</dd></div><div><dt>Active terrain</dt><dd>{text(nav.terrain)}</dd></div><div><dt>Airfields / navaids</dt><dd>{list(nav.airfields).length} / {list(nav.navaids).length}</dd></div><div><dt>Mission overlay</dt><dd>{nav.overlay?'Available':'Unavailable'}</dd></div></dl></section>
      <section className="panel health-card"><span className="eyebrow">EXPORT CAPABILITIES</span><h2>Permission-aware data</h2>{Object.entries(capabilities).length?<dl className="step-details">{Object.entries(capabilities).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{typeof v==='object'?text(obj(v).status??obj(v).verdict):text(v)}</dd></div>)}</dl>:<p className="muted">Unknown. No capability is inferred from absent data.</p>}<p className="micro">No world-object tactical display. Aircraft sensor data remains hidden until fresh export and aircraft validation are established.</p></section></div>
      <section className="panel provenance-panel"><div className="panel-header"><span className="eyebrow">INSTALLED TERRAIN COVERAGE</span><Badge>{coverage.length} maps</Badge></div><div className="coverage-scroll"><table className="coverage-table"><thead><tr><th>Terrain</th><th>Airfields</th><th>Positions</th><th>Navaids</th><th>ATC frequencies</th><th>Runways</th><th>Quarantined</th></tr></thead><tbody>{coverage.map((c,i)=><tr key={i}><td>{text(c.terrain)}</td><td>{format(c.airfields)}</td><td>{format(c.airfield_positions)}</td><td>{format(c.beacons)}</td><td>{format(c.atc_frequencies)}</td><td>{number(c.runways)?format(c.runways):'Unknown'}</td><td>{format(c.quarantined)}</td></tr>)}</tbody></table></div><p className="micro">Position confidence is shown per record. A missing runway export does not imply that an airfield has no runway. Quarantined records are excluded from apparently verified values.</p></section>
      <section className="panel provenance-panel"><div className="panel-header"><span className="eyebrow">AIRCRAFT ADAPTERS</span><Badge>Not yet flight-tested</Badge></div><div className="adapter-grid">{(snapshot?.adapters??[]).map((adapter,i)=><article key={text(adapter.id,i.toString())}><h3>{text(adapter.name??adapter.id??adapter.aircraft)}</h3><Badge tone="amber">{text(adapter.validation_status??adapter.status,'Not yet verified')}</Badge><p className="micro">{Array.isArray(adapter.limitations)?adapter.limitations.join(' '):text(adapter.limitations,'See capability matrix for aircraft-specific validation.')}</p><details><summary>Declared capabilities</summary><pre>{JSON.stringify(adapter.capabilities??{},null,2)}</pre></details></article>)}</div></section>
      <section className="panel provenance-panel"><div className="panel-header"><span className="eyebrow">SOURCE PROVENANCE</span><Badge>{sources.length} files</Badge></div>{sources.length ? sources.map((source,i)=><details key={i}><summary>{text(source.path??source.source_path)}</summary><dl className="step-details"><div><dt>SHA-256</dt><dd className="hash">{text(source.sha256??source.hash??source.source_hash)}</dd></div><div><dt>Modified</dt><dd>{text(source.modified_utc??source.modified_at??source.mtime)}</dd></div><div><dt>Extracted</dt><dd>{text(source.extracted_at??source.extracted_utc)}</dd></div><div><dt>Method / confidence</dt><dd>{text(source.method)} / {text(source.confidence)}</dd></div></dl></details>):<p className="muted">Source provenance is unavailable until a terrain database is loaded.</p>}</section>
      {(h?.notes??[]).map((note,i)=><p key={i} className="notice">{note}</p>)}
  </div>;
}

export default function App() {
  const {snapshot:rawSnapshot,connection,error,pair,receivedAt,diagnostics,connectionHistory,observeAvailability}=useSnapshot();
  const [view,setView]=useDisplayPreference('view'), [brightness,setBrightness]=useDisplayPreference('brightness');
  const [theme,setTheme]=useDisplayPreference('theme'), [textSize,setTextSize]=useDisplayPreference('textSize');
  const [lastAircraftPalette,setLastAircraftPalette]=useState<Palette>('contrast');
  const [token,setToken]=useState(''), [pairError,setPairError]=useState(''), [pairBusy,setPairBusy]=useState(false), [now,setNow]=useState(Date.now());
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
  const effectiveConnection=connection==='connected'&&now-receivedAt>=6000?'delayed':connection;
  const usable=effectiveConnection==='connected';
  const elapsed=receivedAt?Math.max(0,now-receivedAt)/1000:0;
  const telemetryAge=number(rawSnapshot?.health?.telemetry_age_s),displayAge=number(rawSnapshot?.health?.display_age_s);
  const telemetryFresh=usable&&rawSnapshot?.health?.telemetry_fresh===true&&telemetryAge!==undefined&&telemetryAge+elapsed<=3;
  const displaysFresh=usable&&rawSnapshot?.health?.displays_fresh===true&&displayAge!==undefined&&displayAge+elapsed<=3;
  const snapshot=rawSnapshot?{...rawSnapshot,health:{...rawSnapshot.health,telemetry_age_s:telemetryAge===undefined?undefined:telemetryAge+elapsed,display_age_s:displayAge===undefined?undefined:displayAge+elapsed,telemetry_fresh:telemetryFresh,displays_fresh:displaysFresh},guide:{...rawSnapshot.guide,actions:rawSnapshot.guide?.actions?.map(action=>({...action,enabled:action.enabled&&telemetryFresh}))}}:undefined;
  const h=snapshot?.health;
  const awarenessState=awarenessView(snapshot,usable,true,coords(obj(snapshot?.navigation?.ownship))??coords(snapshot?.aircraft??{}),elapsed);
  useEffect(()=>{if(usable)observeAvailability(telemetryFresh,awarenessState.allowed);},[usable,telemetryFresh,awarenessState.allowed,observeAvailability]);
  const currentAircraftPalette=telemetryFresh&&h?.aircraft&&h.dcs_running!==false?aircraftPalette(h.aircraft):undefined;
  const resolvedTheme=theme==='auto'?currentAircraftPalette??lastAircraftPalette:theme;
  useEffect(()=>{if(currentAircraftPalette)setLastAircraftPalette(currentAircraftPalette);},[currentAircraftPalette]);
  useLayoutEffect(()=>{
    document.documentElement.dataset.theme=resolvedTheme;
    document.documentElement.dataset.readability=textSize;
    document.documentElement.style.colorScheme=resolvedTheme==='daylight'?'light':'dark';
  },[resolvedTheme,textSize]);
  const missionName=usable?text(snapshot?.mission?.name,'No mission exported'):'Mission unavailable';
  const status=!usable?effectiveConnection==='delayed'?'Updates delayed':effectiveConnection==='reconnecting'?'Reconnecting':'Offline':h?.status==='Live'&&!telemetryFresh?'Stale telemetry':text(h?.status,'Unknown');
  async function submitPair(e: React.FormEvent){e.preventDefault();setPairBusy(true);try{await pair(token);setToken('');setPairError('');}catch(err){setPairError(err instanceof Error?err.message:'Pairing failed');}finally{setPairBusy(false);}}
  return <><div className={`app ${snapshot?.smart?'smart-layout':''} ${view==='Remote'?'remote-open':''}`} style={{filter:`brightness(${Math.max(35,Math.min(100,brightness))/100})`}}><a className="skip-link" href="#main">Skip to content</a><header className="app-header"><div className="brand"><img src="/icon.svg" alt=""/><div><strong>DCS<span>COPILOT</span></strong><small>FLIGHT COMPANION / 01</small></div></div><div className="session-identity"><span className="eyebrow">AIRCRAFT</span><strong>{text(h?.aircraft,'NO AIRCRAFT')}</strong><span className="header-divider"/><span className="eyebrow">THEATRE</span><strong>{text(h?.terrain,'UNKNOWN')}</strong></div><div className="mission-identity"><span className="eyebrow">MISSION · {usable?text(snapshot?.mission?.status,'Unavailable'):'Offline'}</span><strong title={missionName}>{missionName}</strong></div><div className="header-status"><Badge tone={usable&&h?.telemetry_fresh?'green':'amber'}><i className="dot"/>{status}</Badge><span className="clock">{new Date(now).toLocaleTimeString('en-GB',{hour12:false})}<small>LOCAL</small></span></div></header>
    <nav className="top-nav" aria-label="Main navigation"><div className="view-tabs">{views.map((v,i)=><button key={v} aria-label={v} aria-current={view===v?'page':undefined} className={view===v?'active':''} onClick={()=>setView(v)}><span>{['⌖','⌨','☷','◇','▣','≋','◉','▤'][i]}</span>{v}</button>)}</div><div className="display-settings"><Badge tone={snapshot?.server?.lan_enabled?'amber':''}>{snapshot?.server?.lan_enabled?'LAN CONTROL ENABLED':'LOCAL ACCESS'}</Badge><Appearance theme={theme} setTheme={setTheme} textSize={textSize} setTextSize={setTextSize} brightness={brightness} setBrightness={setBrightness} resolved={resolvedTheme}/><Setup connected={connection==='connected'}/><PairDevice connected={connection==='connected'} lanEnabled={snapshot?.server?.lan_enabled===true}/><label>☀<input type="range" min="35" max="100" value={brightness} onChange={e=>setBrightness(Number(e.target.value))} aria-label="Display brightness"/></label></div></nav>
    <div className={`health-ribbon ${usable&&h?.telemetry_fresh?'':'degraded'}`}><span><i className="dot"/>{usable&&h?.telemetry_fresh?'OWN-SHIP TELEMETRY':'TELEMETRY UNAVAILABLE / STALE'} <b>{age(h?.telemetry_age_s)}</b></span><span>COCKPIT DISPLAYS <b>{h?.displays_fresh&&usable?'Fresh':'Stale / unavailable'} · {age(h?.display_age_s)}</b></span><span className="safety-mode">{snapshot?.server?.remote_armed===true?(snapshot.server.dry_run===false?'Remote LIVE enabled · Guide LIVE enabled':'Remote LIVE enabled · Guide preview'):(snapshot?.server?.dry_run===false?'Guide LIVE enabled · Remote preview':'DRY RUN · NO INPUT SENT')}</span></div>
    {(snapshot?.smart||!usable)&&connection!=='pairing'&&<div className={`readiness-banner ${usable?snapshot?.smart?.status??'':'waiting'}`} role="status"><div><strong>{usable?text(snapshot?.smart?.title,'Dashboard connected'):connection==='connecting'?'Connecting to your Copilot…':'Reconnecting to your Copilot…'}</strong><span>{usable?text(snapshot?.smart?.detail,'Readiness is shown above.'):'Live connection unavailable. This page reconnects automatically; ownship guidance and command submission are disabled.'}</span></div><div className="readiness-badges">{usable&&snapshot?.smart?.binding_refresh?.status&&<Badge tone={snapshot.smart.binding_refresh.status==='Error'?'amber':''}>Bindings: {snapshot.smart.binding_refresh.status}</Badge>}{usable&&snapshot?.smart?.autostart&&<Badge tone={snapshot.smart.autostart.enabled?'green':'amber'}>{(snapshot.smart.autostart.state??snapshot.smart.autostart.status)==='Unavailable'?'AUTO-START UNAVAILABLE':snapshot.smart.autostart.state==='Paused by manual stop'?'AUTOMATIC START PAUSED':snapshot.smart.autostart.enabled?'AUTOMATIC START ON':'AUTOMATIC START OFF'}</Badge>}</div></div>}
    <main id="main"><div hidden={view!=='Navigation Scope'}><NavigationScope snapshot={snapshot} usable={usable} elapsed={elapsed}/></div>{view==='Remote'?<Remote snapshot={snapshot} usable={usable} elapsed={elapsed} brightness={brightness}/>:view==='Controls'?<Controls snapshot={snapshot} usable={usable}/>:view==='Guide'?<Guide snapshot={snapshot} usable={usable}/>:view==='Sensors'?<Sensors snapshot={snapshot} usable={usable} elapsed={elapsed}/>:view==='Cockpit'?<Cockpit snapshot={snapshot} usable={usable} elapsed={elapsed}/>:view==='Flight data'?<FlightData snapshot={snapshot} usable={usable} elapsed={elapsed}/>:view==='Data Health'?<Health snapshot={snapshot} connection={effectiveConnection} receivedAt={receivedAt} connectionPanel={<ConnectionHealth connection={effectiveConnection} receivedAt={receivedAt} now={now} error={error} diagnostics={diagnostics} history={connectionHistory}/>}/>:null}</main>

    <footer className="app-footer"><label className="mobile-brightness">Display brightness<input type="range" min="35" max="100" value={brightness} onChange={e=>setBrightness(Number(e.target.value))} aria-label="Tablet display brightness"/></label><span><i className="dot"/>OFFLINE-CAPABLE APP SHELL <span className="footer-separator">/</span> LOCAL DATA ONLY</span><span>Not yet flight-tested <span className="footer-separator">/</span> {text(snapshot?.server?.version,'MVP')}</span></footer>
    {connection==='pairing'&&<div className="pairing-overlay"><form className="pairing-card panel" onSubmit={e=>void submitPair(e)}><img src="/icon.svg" alt=""/><span className="eyebrow">PAIR THIS DEVICE</span><h1>Your cockpit, connected.</h1><p>Enter the pairing token shown by the dashboard’s tablet start script on your DCS computer.</p><label>Pairing token<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} required autoFocus/></label><button className="primary-button" disabled={pairBusy}>{pairBusy?'Pairing…':'Pair device'}</button>{(pairError||error)&&<p className="error" role="alert">{pairError||error}</p>}<p className="micro">The token is not saved in browser storage. Live data and controls require an authenticated session.</p></form></div>}
  </div>{createPortal(<nav className="mobile-view-nav" aria-label="Mobile navigation" style={{filter:`brightness(${Math.max(35,Math.min(100,brightness))/100})`}}>{(['Navigation Scope','Remote','Controls','Guide','Sensors','Cockpit','Flight data','Data Health'] as const).map(v=><button key={v} aria-label={v} aria-current={view===v?'page':undefined} onClick={()=>{setView(v);window.scrollTo({top:0,behavior:'instant'});}}>{v==='Navigation Scope'?'Scope':v==='Data Health'?'Health':v}</button>)}</nav>,document.body)}</>;
}
