import { useCallback, useEffect, useRef, useState } from 'react';
import { request } from './api';

export type DisplayFeedPanelId='left_mdi'|'right_mdi'|'ampcd';
type DisplayKind='virtual'|'physical'|'unknown';
interface ExportMonitor {id:string;name:string;primary:boolean;x:number;y:number;width:number;height:number;kind?:DisplayKind;adapter_description?:string;}
export interface DisplayFeedState {
  enabled:boolean;can_edit:boolean;status:string;detail?:string;revision:string;aircraft?:string|null;
  panels:Array<{id:DisplayFeedPanelId;label:string;status:string;detail?:string;width?:number;height?:number}>;
  setup:{status:string;detail?:string;dcs_running?:boolean;monitors:ExportMonitor[];can_apply:boolean;can_restore:boolean;can_plan?:boolean;eligible_monitor_ids?:string[];recommended_monitor_id?:string|null;monitor_id?:string|null;export_kind?:DisplayKind;physical_monitors_preserved?:boolean;
    plan?:{id:string;summary:string;monitor_id?:string;main_monitor?:unknown;export_monitor?:unknown;export_kind?:DisplayKind;physical_monitors_preserved?:boolean;window?:unknown;panels?:unknown;changes?:unknown;restart_required:true}};
}
function valid(value:unknown):value is DisplayFeedState {const item=value as DisplayFeedState;return !!item&&typeof item==='object'&&typeof item.enabled==='boolean'&&typeof item.can_edit==='boolean'&&typeof item.status==='string'&&typeof item.revision==='string'&&Array.isArray(item.panels)&&!!item.setup&&Array.isArray(item.setup.monitors);}
export function useDisplayFeedStatus(usable:boolean,context:string){
  const [entry,setEntry]=useState<{context:string;value:DisplayFeedState}>(),[error,setError]=useState('');
  const epoch=useRef(0),pending=useRef<AbortController|undefined>(undefined),requestId=useRef(0);
  const update=useCallback((value:unknown)=>{if(valid(value)){requestId.current++;setEntry({context,value});setError('');}else throw new Error('Display image status is unavailable.');},[context]);
  const refresh=useCallback(async()=>{if(!usable||pending.current||document.visibilityState==='hidden')return;const generation=epoch.current,id=++requestId.current,controller=new AbortController();pending.current=controller;try{const value=await request('/api/display-feed',undefined,{timeoutMs:3500,signal:controller.signal});if(generation===epoch.current&&id===requestId.current){if(!valid(value))throw new Error();setEntry({context,value});setError('');}}catch{if(generation===epoch.current&&id===requestId.current&&!controller.signal.aborted){setEntry(undefined);setError('Display image service is unavailable. Exported text is still available.');}}finally{if(pending.current===controller)pending.current=undefined;}},[usable,context]);
  useEffect(()=>{epoch.current++;setEntry(undefined);setError('');void refresh();const timer=setInterval(()=>void refresh(),5000);const visibility=()=>{if(document.visibilityState==='hidden')pending.current?.abort();else void refresh();};document.addEventListener('visibilitychange',visibility);return()=>{epoch.current++;clearInterval(timer);pending.current?.abort();pending.current=undefined;document.removeEventListener('visibilitychange',visibility);};},[refresh]);
  return {feed:usable&&entry?.context===context?entry.value:undefined,error,refresh,update};
}
const fieldNames:Record<string,string>={multiMonitorSetup:'Display layout',monitorSetup:'Display layout',width:'DCS window width',height:'DCS window height',aspect:'Window aspect ratio',fullScreen:'Window mode'};
function setting(field:string,value:unknown){if(field==='fullScreen')return value===true?'Full screen':'Windowed';if(field==='multiMonitorSetup'||field==='monitorSetup')return value==='1camera'||value==='1 Screen'?'Single monitor':typeof value==='string'&&value.toLowerCase().includes('companion')?'Companion display exports':String(value??'Unknown');if(typeof value==='number')return `${Number.isInteger(value)?value:value.toFixed(2)}${field==='width'||field==='height'?' pixels':''}`;return typeof value==='string'?value:'Unknown';}
function rectangle(value:unknown){const item=value as {width?:number;height?:number}|undefined;return item&&Number.isFinite(item.width)&&Number.isFinite(item.height)?`${item.width} × ${item.height} pixels`:'Dimensions unavailable';}
function PlanArrangement({plan}:{plan:NonNullable<DisplayFeedState['setup']['plan']>}){const panels=plan.panels&&typeof plan.panels==='object'?Object.entries(plan.panels):[];return <dl className="display-feed-review-list"><div><dt>Main cockpit</dt><dd>{typeof plan.main_monitor==='string'?plan.main_monitor:'Current primary monitor'}</dd></div><div><dt>{plan.export_kind==='virtual'?'Virtual export display':'Reserved export monitor'}</dt><dd>{typeof plan.export_monitor==='string'?plan.export_monitor:'Selected export display'} · {plan.export_kind==='virtual'?'virtual screen reserved for DCS':'entire monitor reserved for DCS'}</dd></div><div><dt>Combined DCS window</dt><dd>{rectangle(plan.window)} · windowed</dd></div>{panels.map(([id,value])=><div key={id}><dt>{({left_mdi:'Left DDI',right_mdi:'Right DDI',ampcd:'AMPCD'} as Record<string,string>)[id]??'Display'}</dt><dd>{rectangle(value)}</dd></div>)}</dl>;}
function ExportChoice({kind,preserved}:{kind?:DisplayKind;preserved?:boolean}){return <p className={`display-feed-choice ${kind==='virtual'&&preserved===true?'virtual':'reservation'}`}>{kind==='virtual'?preserved===true?'Virtual display only. Your physical monitors remain available for other apps.':'Virtual display selected. The layout has not yet verified that your other screens remain free.':kind==='physical'?'Physical display selected. The entire selected monitor will be reserved for DCS exports; other apps cannot remain visible on it.':'Display type is unknown. Treat the entire selected screen as reserved for DCS exports.'}</p>;}
function PlanChanges({value}:{value:unknown}){if(!Array.isArray(value))return null;return <dl className="display-feed-review-list">{value.filter(item=>item&&typeof item.field==='string').map((item,index)=><div key={index}><dt>{fieldNames[item.field]??'Display setting'}</dt><dd><span>{setting(item.field,item.before)}</span><span aria-label="changes to"> → </span><strong>{setting(item.field,item.after)}</strong></dd></div>)}</dl>;}
export default function DisplayFeedSetup({feed,error,usable,dcsRunning,onRefresh,onStatus}:{feed?:DisplayFeedState;error:string;usable:boolean;dcsRunning:boolean;onRefresh:()=>void;onStatus:(value:unknown)=>void}){
  const [monitor,setMonitor]=useState(''),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[reviewed,setReviewed]=useState(false);
  const setup=feed?.setup,plan=setup?.plan,monitors=(setup?.monitors??[]).filter(item=>!item.primary);
  const appliedLayout=!!setup?.monitor_id||setup?.status==='active'||setup?.status==='pending-restart';
  const eligible=(item:ExportMonitor)=>!setup?.eligible_monitor_ids||setup.eligible_monitor_ids.includes(item.id);
  const virtuals=monitors.filter(item=>item.kind==='virtual'),recommended=virtuals.find(item=>eligible(item)&&item.id===setup?.recommended_monitor_id)??virtuals.find(eligible);
  const selected=monitors.some(item=>item.id===monitor)?monitor:recommended?.id??'',selectedMonitor=monitors.find(item=>item.id===selected),planMatches=!plan?.monitor_id||plan.monitor_id===selected;
  const closed=!dcsRunning&&setup?.dcs_running!==true,canEdit=feed?.can_edit===true,canPlan=setup?.can_plan!==false&&(!setup?.eligible_monitor_ids||setup.eligible_monitor_ids.includes(selected));
  useEffect(()=>setReviewed(false),[plan?.id,selected,dcsRunning]);
  async function change(endpoint:string,payload:unknown){if(busy||!usable||!canEdit)return;setBusy(true);setActionError('');try{const result=await request(`/api/display-feed/${endpoint}`,payload,{timeoutMs:8000});onStatus(result);setReviewed(false);}catch(error){setActionError(error instanceof Error?error.message:'The display setup request failed. Refresh its status before trying again.');}finally{setBusy(false);}}
  return <details className="panel display-feed-setup"><summary>Live display images · {feed?.enabled?feed.status:'capture off'}</summary><p>{feed?.detail||error||'Read the actual DDI and AMPCD export regions from your DCS computer.'}</p>{error&&feed&&<p>{error}</p>}<p>A virtual display can host the DDI and AMPCD images while your physical monitors stay available for other apps. View those images here or on a paired phone or tablet. Only the registered display regions are shared while DCS is foreground.</p>
    <div className="display-feed-setup-status"><strong>{({'not-configured':'Not configured','pending-restart':'Restart DCS',active:'Layout ready',changed:'Layout changed',unavailable:'Unavailable'} as Record<string,string>)[setup?.status??'']??setup?.status??'Unavailable'}</strong><span>{setup?.detail}</span><button disabled={!usable||busy} onClick={onRefresh}>Refresh display setup</button></div>
    {canEdit?<>{!recommended&&!appliedLayout&&<p className="display-feed-virtual-help">{virtuals.length?'A virtual display was detected, but its current Windows arrangement is not eligible. Check the layout details above on your DCS computer, then refresh.':'No virtual display is detected. Install and enable a virtual display driver on your DCS computer, then refresh this page. This page does not install drivers or change the Windows display arrangement.'} A physical display is an optional alternative only if you choose to reserve it for DCS.</p>}<label>Dedicated export monitor<select aria-label="Dedicated export monitor" value={selected} disabled={busy||!monitors.length} onChange={event=>setMonitor(event.target.value)}>{!selected&&<option value="">Choose an export display</option>}{monitors.map(item=><option key={item.id} value={item.id} disabled={!eligible(item)}>{item.kind==='virtual'?'Virtual':item.kind==='physical'?'Physical · reserves monitor':'Unknown type · reserves screen'} — {item.adapter_description&&item.kind==='virtual'?item.adapter_description:item.name} · {item.width} × {item.height}</option>)}</select></label>{selectedMonitor&&<ExportChoice kind={selectedMonitor.kind} preserved={planMatches&&plan?.export_kind===selectedMonitor.kind?plan?.physical_monitors_preserved:undefined}/>}<button disabled={!usable||busy||!selected||!canPlan} onClick={()=>void change('plan',{monitor_id:selected})}>Prepare display layout</button>
      {appliedLayout&&setup?.export_kind&&<ExportChoice kind={setup.export_kind} preserved={setup.physical_monitors_preserved}/>}
      {plan&&<section className="display-feed-plan" aria-label="Display layout review"><h3>Review display layout</h3><p>{plan.summary}</p><ExportChoice kind={plan.export_kind} preserved={plan.physical_monitors_preserved}/><p>This changes DCS display settings and creates a backup. Close DCS before applying; restart DCS afterwards so the export layout is loaded.</p><details><summary>Planned monitor and window arrangement</summary><PlanArrangement plan={plan}/></details><div className="display-feed-changes"><strong>Settings to change</strong><PlanChanges value={plan.changes}/></div>{!planMatches&&<p>Prepare a new layout to review your changed display choice.</p>}<label className="display-feed-review"><input type="checkbox" checked={reviewed} disabled={!planMatches} onChange={event=>setReviewed(event.target.checked)}/>I reviewed the layout and will {plan.export_kind==='virtual'?'use the virtual display':'reserve the selected screen'} for DCS exports.</label><button disabled={!usable||busy||!closed||setup?.can_apply!==true||!reviewed||!planMatches} onClick={()=>void change('apply',{plan_id:plan.id})}>Apply reviewed layout</button></section>}
      {!closed&&<p className="display-feed-requirement">Close DCS before applying or restoring its display layout.</p>}
      <div className="display-feed-setup-actions"><button disabled={!usable||busy||!closed||setup?.can_restore!==true} onClick={()=>void change('restore',{})}>Restore previous display layout</button><button disabled={!usable||busy||!feed.enabled&&feed.status==='Setup required'} onClick={()=>void change('enabled',{enabled:!feed.enabled})}>{feed.enabled?'Disable display capture':'Enable display capture'}</button></div><p>Capture starts only when you enable it. It resets when the companion restarts; live cockpit controls are separate.</p>
    </>:<p className="display-feed-pc-note">Prepare the display layout and enable capture on your DCS computer. This paired device can view the enabled display images.</p>}{actionError&&<p role="alert">{actionError}</p>}</details>;
}
