import { createPortal } from 'react-dom';
import { useCallback, useEffect, useRef, useState } from 'react';
import { request } from './api';
import type { Snapshot } from './types';
import { age, list, number, obj, text, uuid } from './utils';
import { panelNames, useDeviceLayout, useWorkspace } from './workspace';
import type { PanelId } from './workspace';
import type { RemotePanel, RemoteState } from './remote-types';
import WorkspaceEditor from './WorkspaceEditor';
import RemoteWorkflows from './RemoteWorkflows';
import DisplayFeed from './DisplayFeed';
import DisplayFeedSetup, { useDisplayFeedStatus } from './DisplayFeedSetup';
import type { DisplayFeedState, DisplayFeedPanelId } from './DisplayFeedSetup';
import {DisplayStreamProvider} from './display-stream';
import type {DisplaySources} from './display-stream';
import CockpitBezel, {RemoteControl} from './CockpitBezel';
import {cockpitDisplays} from './cockpit-layout';
import './display-feed.css';

const catalogIds:Record<PanelId,string>={'left-ddi':'left_mdi','right-ddi':'right_mdi',ufc:'ufc',ampcd:'ampcd',navigation:'navigation',workflows:'workflows'};
const displayIds:Partial<Record<PanelId,number>>={'left-ddi':2,'right-ddi':3,ampcd:4,ufc:6};
function DisplayReadout({id,label:explicitLabel,displayId,snapshot,usable,elapsed}:{id?:PanelId;label?:string;displayId?:string;snapshot?:Snapshot;usable:boolean;elapsed:number}){
  const label=explicitLabel??(id?panelNames[id]:'Display');
  const cockpit=obj(snapshot?.cockpit),caps=obj(snapshot?.health?.export_capabilities);
  const denied=['cockpit','ownship','sensor'].some(key=>['denied','export denied'].includes(text(obj(caps[key]).status??obj(caps[key]).verdict??caps[key],'').toLowerCase()));
  const display=list(cockpit.displays).find(item=>String(item.id)===String(displayId??(id?displayIds[id]:undefined)));
  const displayAge=number(display?.age_s),currentAge=displayAge===undefined?undefined:displayAge+elapsed;
  const fresh=usable&&!denied&&cockpit.aircraft===snapshot?.health?.aircraft&&snapshot?.health?.telemetry_fresh===true&&display?.status==='Available'&&currentAge!==undefined&&currentAge>=0&&currentAge<=3;
  return <div className="remote-readout" aria-label={`${label} exported readout`}><div className="remote-readout-status"><span>EXPORTED TEXT</span><span>{fresh?`Current · ${age(currentAge)}`:denied?'Export denied':display?'Stale / unavailable':'Not exported'}</span></div>{fresh&&list(display?.elements).length?<dl>{list(display?.elements).map((element,index)=><div key={index}><dt>{text(element.name)}</dt><dd>{text(element.value)}</dd></div>)}</dl>:<p>No current display text available.</p>}<small>Text only · no video or reconstructed graphics</small></div>;
}
function CockpitPanel({id,panel,style,snapshot,usable,elapsed,enabled,busy,onTap,feed}:{id:PanelId;panel?:RemotePanel;style:'cockpit'|'touch';snapshot?:Snapshot;usable:boolean;elapsed:number;enabled:boolean;busy:boolean;onTap:(id:string)=>void;feed?:DisplayFeedState}){
  const buttons=panel?.buttons??[],display=cockpitDisplays(snapshot?.health?.aircraft??'',snapshot?.cockpit).find(item=>item.workspaceId===id);
  const bezel=style==='cockpit'&&display?.bezel&&display.controlPanelId;
  const textReadout=<DisplayReadout id={id} snapshot={snapshot} usable={usable} elapsed={elapsed}/>;
  const readout=display?.nativePanelId?<DisplayFeed key={id} panelId={display.nativePanelId} label={display.label} feed={feed} aircraft={snapshot?.health?.aircraft} session={snapshot?.health?.session} usable={usable} textReadout={textReadout} surround={bezel?screen=><CockpitBezel panel={panel} controlPanelId={display.controlPanelId!} layout={display.bezel!} label={display.label} enabled={enabled} busy={busy} onTap={onTap}>{screen}</CockpitBezel>:undefined}/>:textReadout;
  return <><div className="remote-panel-heading"><h2>{panel?.label??panelNames[id]}</h2><span className="badge">{buttons.filter(button=>button.available).length} / {buttons.length} bound</span></div>{id!=='navigation'&&readout}{!bezel&&<div className={`remote-control-grid ${id==='ufc'?'ufc-controls':''}`}>{buttons.map(button=><RemoteControl key={button.id} button={button} enabled={enabled} busy={busy} onTap={onTap}/>)}</div>}{!buttons.length&&<p>No registered controls for this panel. Display readouts remain independent.</p>}</>;
}
export default function Remote({snapshot,usable,elapsed,brightness}:{snapshot?:Snapshot;usable:boolean;elapsed:number;brightness:number}){
  const aircraft=text(snapshot?.health?.aircraft,'unknown'),device=useDeviceLayout();
  const displayContext=JSON.stringify([snapshot?.health?.aircraft,snapshot?.health?.session]);
  const displayFeed=useDisplayFeedStatus(usable,displayContext);
  const [workspace,setWorkspace]=useWorkspace(aircraft,device),[remote,setRemote]=useState<RemoteState>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[stopping,setStopping]=useState(false),[controller,setController]=useState(''),[selected,setSelected]=useState<PanelId|'all'>('all'),[second,setSecond]=useState<PanelId>('left-ddi');
  const [sources,setSources]=useState<DisplaySources>({});
  const setSource=useCallback((id:DisplayFeedPanelId,source:'image'|'text')=>setSources(current=>({...current,[id]:source})),[]);
  const pollInFlight=useRef(false),statusInFlight=useRef(false),generation=useRef(0),heartbeatInFlight=useRef(false),sequence=useRef(0),accepted=useRef(0),pendingCommands=useRef(0),pendingStop=useRef(false);
  const mergeStatus=useCallback((value:Partial<RemoteState>,requestNumber:number)=>{if(requestNumber<accepted.current||typeof value.controller_connected!=='boolean')return;accepted.current=requestNumber;setRemote(current=>current?{...current,...value,panels:current.panels,workflows:current.workflows,scripts:current.scripts,can_edit:value.can_edit??current.can_edit,can_arm:value.can_arm??current.can_arm}:current);},[]);
  const refresh=useCallback(async()=>{if(!usable||pollInFlight.current)return;const version=generation.current,requestNumber=++sequence.current;pollInFlight.current=true;try{const value=await request('/api/remote',undefined,{timeoutMs:4000});if(version!==generation.current)return;if(!value||!Array.isArray(value.panels)||!Array.isArray(value.workflows))throw new Error('Remote controls are unavailable.');const catalog={panels:value.panels,workflows:value.workflows,scripts:Array.isArray(value.scripts)?value.scripts:[],can_edit:value.can_edit,can_arm:value.can_arm};if(requestNumber<accepted.current)setRemote(current=>current?{...current,...catalog}:undefined);else{accepted.current=requestNumber;setRemote({...value,...catalog});}setError(previous=>previous.startsWith('Remote controls are unavailable.')?'':previous);}catch{if(version===generation.current){setRemote(undefined);setController('');setError('Remote controls are unavailable. Reconnect after the companion responds.');}}finally{pollInFlight.current=false;}},[usable,aircraft]);
  const refreshStatus=useCallback(async()=>{if(!usable||statusInFlight.current)return;const version=generation.current,requestNumber=++sequence.current;statusInFlight.current=true;try{const value=await request('/api/remote/status',undefined,{timeoutMs:2000});if(version===generation.current)mergeStatus(value,requestNumber);}catch{if(version===generation.current){setController('');setError('Run status is unavailable. No action will be repeated. Reconnect to check its outcome.');}}finally{statusInFlight.current=false;}},[usable,aircraft,mergeStatus]);
  useEffect(()=>{generation.current++;setRemote(undefined);setController('');void refresh();const timer=setInterval(()=>void refresh(),10000);return()=>{generation.current++;clearInterval(timer);};},[refresh,snapshot?.health?.session,snapshot?.bindings?.source_fingerprint,snapshot?.bindings?.status]);
  useEffect(()=>{if(!remote?.busy&&!remote?.active_run)return;const timer=setInterval(()=>void refreshStatus(),250);return()=>clearInterval(timer);},[Boolean(remote?.busy||remote?.active_run),refreshStatus]);
  useEffect(()=>{if(!controller||!usable)return;let cancelled=false;const beat=async()=>{if(heartbeatInFlight.current)return;const requestNumber=++sequence.current;heartbeatInFlight.current=true;try{const value=await request('/api/remote/heartbeat',{connection_id:controller},{timeoutMs:2500});if(!cancelled)mergeStatus(value,requestNumber);}catch{if(!cancelled){setController('');setError('Control connection lost. Reconnect explicitly; actions are never repeated.');}}finally{heartbeatInFlight.current=false;}};void beat();const timer=setInterval(()=>void beat(),2000);return()=>{cancelled=true;clearInterval(timer);};},[controller,usable,mergeStatus]);
  const matching=remote?.aircraft===aircraft,enabled=Boolean(usable&&matching&&controller&&remote?.controller_connected&&snapshot?.health?.telemetry_fresh),running=busy||remote?.busy===true;
  const canArm=remote?.can_arm??remote?.can_edit,connected=Boolean(usable&&matching&&controller&&remote?.controller_connected),live=connected&&remote?.armed&&remote.mode==='live';
  const controlStatus=!controller?'Controls disconnected':!connected?'Connecting controls…':live?'Live controls enabled for this flight':'Preview · no input sent';
  const controlHelp=!controller?canArm?'Choose Connect controls, then Enable live controls on this screen.':'Choose Connect controls to preview registered controls on this screen.':!connected?'Waiting for this screen to connect.':live?'Buttons on this screen now send cockpit inputs. Keep DCS focused on your PC. Disconnect controls to end this screen’s connection.':canArm?'Connected in preview. Choose Enable live controls to send cockpit inputs from this screen. Keep DCS focused on your PC.':'Connected in preview. This screen can preview registered controls without sending cockpit inputs.';
  async function command(path:string,payload:unknown){const isStop=path==='/api/remote/stop';if(!usable||isStop&&pendingStop.current||!isStop&&pendingCommands.current>0)return;if(isStop){pendingStop.current=true;setStopping(true);}pendingCommands.current++; const version=generation.current,requestNumber=++sequence.current;setBusy(true);setError('');try{const result=await request(path,payload,{timeoutMs:5000});if(version!==generation.current)return;if(typeof result.step_count==='number'&&result.id&&requestNumber>=accepted.current){accepted.current=requestNumber;const active=['Queued','Running'].includes(result.status);setRemote(current=>current?{...current,busy:active,active_run:active?result:null,last_run:result}:current);}else mergeStatus(result,requestNumber);void refreshStatus();}catch(error){setError(`${error instanceof Error?error.message:'Request failed.'} No action was repeated. Check run status before trying again.`);}finally{pendingCommands.current=Math.max(0,pendingCommands.current-1);setBusy(pendingCommands.current>0);if(isStop){pendingStop.current=false;setStopping(false);}}}
  function tap(action_id:string){if(enabled&&!running)void command('/api/remote/tap',{idempotency_key:uuid(),action_id});}
  function run(workflow_id:string){if(enabled&&!running)void command('/api/remote/run',{idempotency_key:uuid(),workflow_id});}
  function script(script_id:string){if(enabled&&!running)void command('/api/remote/script',{idempotency_key:uuid(),script_id});}
  const visible=workspace.panels.filter(panel=>panel.visible&&(panel.id==='workflows'||remote?.panels.some(item=>item.id===catalogIds[panel.id])||aircraft==='FA-18C_hornet'&&panel.id!=='navigation'));
  const primary=selected!=='all'&&visible.some(panel=>panel.id===selected)?selected:visible[0]?.id;
  const secondary=visible.some(panel=>panel.id===second)&&second!==primary?second:visible.find(panel=>panel.id!==primary)?.id;
  const displays=cockpitDisplays(aircraft,snapshot?.cockpit);
  const overviewAvailable=displays.length>0,overview=overviewAvailable&&selected==='all';
  const overviewIds=displays.map(display=>display.workspaceId).filter((id):id is PanelId=>!!id);
  const shown=overview?overviewIds:device==='phone'?[primary]:[primary,secondary];
  const streamPanels=shown.filter((id):id is PanelId=>!!id&&overviewIds.includes(id)).map(id=>catalogIds[id] as DisplayFeedPanelId).filter(id=>(sources[id]??(displayFeed.feed?.enabled?'image':'text'))==='image');
  return <DisplayStreamProvider feed={displayFeed.feed} usable={usable} aircraft={snapshot?.health?.aircraft} session={snapshot?.health?.session} requested={streamPanels} sources={sources} setSource={setSource}><div className="page-view remote-workspace" data-device={device}><div className="page-title"><div><span className="eyebrow">YOUR AIRCRAFT · YOUR WORKSPACE</span><h1>Remote<span className="title-period">.</span></h1><p>{aircraft==='unknown'?'Waiting for an aircraft':aircraft} · {device} layout</p></div><label className="remote-style">Panel style<select aria-label="Remote panel style" value={workspace.style} onChange={event=>setWorkspace({...workspace,style:event.target.value as 'cockpit'|'touch'})}><option value="touch">Large touch</option><option value="cockpit">Cockpit</option></select></label></div>
    <div className="panel remote-session"><div><strong>{controlStatus}</strong><p>{controlHelp}</p>{remote?.reason&&<small>{remote.reason}</small>}{live&&remote?.arm_expires_at&&<small>Live arm expires at {new Date(remote.arm_expires_at*1000).toLocaleTimeString()}</small>}</div><button disabled={!usable||!remote||busy} onClick={()=>{if(controller){const connection_id=controller;setController('');void command('/api/remote/disconnect',{connection_id});}else{setError('');setController(uuid());}}}>{controller?'Disconnect controls':'Connect controls'}</button>{canArm&&<button disabled={!connected||busy} onClick={()=>void command('/api/remote/arm',{enabled:!live})}>{live?'Disarm live controls':'Enable live controls'}</button>}<button disabled={(!remote?.active_run&&!busy)||stopping||!usable} onClick={()=>void command('/api/remote/stop',{})}>Stop current run</button></div>{error&&<p role="alert" className="notice error">{error}</p>}{!remote&&<p role="status">Waiting for the remote control catalogue.</p>}
    {(remote?.active_run??remote?.last_run)&&<div className="panel remote-result" role="status"><strong>{(remote?.active_run??remote?.last_run)?.status} · {(remote?.active_run??remote?.last_run)?.mode}</strong><p>{(remote?.active_run??remote?.last_run)?.message}</p></div>}
    {device==='phone'&&(remote?.active_run||busy)&&createPortal(<button className="remote-emergency-stop" style={{filter:`brightness(${Math.max(35,Math.min(100,brightness))/100})`}} disabled={stopping||!usable} onClick={()=>void command('/api/remote/stop',{})}>Stop remote run</button>,document.body)}
    <DisplayFeedSetup feed={displayFeed.feed} error={displayFeed.error} usable={usable} dcsRunning={snapshot?.health?.dcs_running===true} onRefresh={()=>void displayFeed.refresh()} onStatus={displayFeed.update}/>
    <WorkspaceEditor workspace={workspace} onChange={setWorkspace} device={device}/><div className="remote-panel-picker" role="group" aria-label="Choose cockpit panel">{overviewAvailable&&<button aria-pressed={overview} onClick={()=>setSelected('all')}>All displays</button>}{visible.map(panel=><button key={panel.id} aria-pressed={!overview&&primary===panel.id} onClick={()=>setSelected(panel.id)}>{panelNames[panel.id]}</button>)}</div>{!overview&&device!=='phone'&&visible.length>1&&<label className="remote-second">Second panel<select aria-label="Second cockpit panel" value={secondary??''} onChange={event=>setSecond(event.target.value as PanelId)}>{visible.filter(panel=>panel.id!==primary).map(panel=><option key={panel.id} value={panel.id}>{panelNames[panel.id]}</option>)}</select></label>}
    {overview?<section className="display-overview" aria-label="All cockpit displays"><div className="display-overview-heading"><h2>All displays</h2><p>{aircraft==='FA-18C_hornet'?device==='phone'?'Left DDI · AMPCD · Right DDI. Tap the buttons beside each display option.':'Left DDI · AMPCD · Right DDI. Bezel buttons match the cockpit.':'Exported displays for this aircraft.'}</p></div><div className="display-overview-grid" data-display-count={displays.length}>{displays.map(display=>{
      const panel=matching?remote?.panels.find(item=>item.id===display.controlPanelId):undefined;
      const textReadout=<DisplayReadout label={display.label} displayId={display.textDisplayId} snapshot={snapshot} usable={usable} elapsed={elapsed}/>;
      const bezel=display.bezel&&display.controlPanelId;
      return <section className="panel display-overview-card" key={display.id} data-display-id={display.id}>
        <div className="display-overview-card-heading"><div><h3>{display.label}</h3>{bezel&&<small>{panel?.buttons.filter(button=>button.available).length??0} / 20 buttons bound</small>}</div>{display.workspaceId&&<button aria-label={`Open ${display.label} controls`} onClick={()=>setSelected(display.workspaceId!)}>Open panel</button>}</div>
        {display.nativePanelId?<DisplayFeed panelId={display.nativePanelId} label={display.label} feed={displayFeed.feed} usable={usable} textReadout={textReadout} surround={bezel?screen=><CockpitBezel panel={panel} controlPanelId={display.controlPanelId!} layout={display.bezel!} label={display.label} enabled={enabled} busy={running} onTap={tap}>{screen}</CockpitBezel>:undefined}/>:<div role="region" aria-label={`${display.label} display view`}>{textReadout}</div>}
      </section>;
    })}</div></section>:<div className="remote-panel-grid">{shown.filter((id,index,array)=>id&&array.indexOf(id)===index).map(id=>{const panel=workspace.panels.find(item=>item.id===id)!;return <div key={id} className={`remote-panel-slot panel-size-${panel.size}`}>{id==='workflows'?remote?<RemoteWorkflows remote={remote} snapshot={snapshot} elapsed={elapsed} enabled={enabled} busy={busy} stopping={stopping} onRun={run} onScript={script} onStop={()=>void command('/api/remote/stop',{})} onRefresh={()=>void refresh()}/>:<p>Workflow catalogue unavailable.</p>:<section className={`panel remote-cockpit-panel style-${panel.style==='inherit'?workspace.style:panel.style}`}><CockpitPanel id={id!} panel={matching?remote?.panels.find(item=>item.id===catalogIds[id!]):undefined} style={panel.style==='inherit'?workspace.style:panel.style} snapshot={snapshot} usable={usable} elapsed={elapsed} enabled={enabled} busy={running} onTap={tap} feed={displayFeed.feed}/></section>}</div>;})}</div>}{!overview&&!visible.length&&<p className="panel empty-state">No panels are visible. Open Edit workspace to enable panels.</p>}
  </div></DisplayStreamProvider>;
}
