import { useState } from 'react';
import { request } from './api';
import { list, number, obj, text, uuid } from './utils';
import type { Snapshot } from './types';
import type { RemoteState, Workflow, WorkflowStep } from './remote-types';
export default function RemoteWorkflows({remote,snapshot,elapsed,enabled,busy,stopping,onRun,onScript,onStop,onRefresh}:{remote:RemoteState;snapshot?:Snapshot;elapsed:number;enabled:boolean;busy:boolean;stopping:boolean;onRun:(id:string)=>void;onScript:(id:string)=>void;onStop:()=>void;onRefresh:()=>void}){
  const [draft,setDraft]=useState<Workflow>(),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const buttons=remote.panels.flatMap(panel=>panel.buttons),run=remote.active_run??remote.last_run;
  const displays=list(obj(snapshot?.cockpit).displays).filter(display=>display.status==='Available'&&number(display.age_s)!==undefined&&Number(display.age_s)+elapsed<=3&&snapshot?.health?.telemetry_fresh===true&&obj(snapshot?.cockpit).aircraft===snapshot?.health?.aircraft);
  const fields=displays.flatMap(display=>list(display.elements).map(element=>({display_id:String(display.id),name:text(element.name,''),value:text(element.value,'')}))).filter(field=>field.name);
  const patch=(index:number,step:WorkflowStep)=>draft&&setDraft({...draft,steps:draft.steps.map((item,i)=>i===index?step:item)});
  function add(type:WorkflowStep['type']){if(!draft||draft.steps.length>=32)return;let step:WorkflowStep;if(type==='action')step={type,action_id:buttons[0]?.id??''};else if(type==='delay')step={type,seconds:1};else if(type==='wait')step={type,display_id:fields[0]?.display_id??'',name:fields[0]?.name??'',equals:fields[0]?.value??'',timeout_s:5};else step={type,script_id:remote.scripts[0]?.id??''};setDraft({...draft,steps:[...draft.steps,step]});}
  async function save(){if(!draft||saving)return;setSaving(true);setError('');try{await request('/api/remote/workflows',draft,{timeoutMs:5000});setDraft(undefined);onRefresh();}catch(error){setError(error instanceof Error?error.message:'Workflow could not be saved.');}finally{setSaving(false);}}
  async function remove(workflow:Workflow){if(!confirm(`Delete workflow “${workflow.name}”?`))return;setSaving(true);setError('');try{await request(`/api/remote/workflows/${encodeURIComponent(workflow.id)}`,undefined,{method:'DELETE',timeoutMs:5000});onRefresh();}catch(error){setError(error instanceof Error?error.message:'Workflow could not be deleted.');}finally{setSaving(false);}}
  function move(index:number,delta:number){if(!draft)return;const steps=[...draft.steps];[steps[index],steps[index+delta]]=[steps[index+delta],steps[index]];setDraft({...draft,steps});}
  return <section className="panel remote-workflows" aria-label="Remote workflows"><div className="remote-panel-heading"><h2>Workflows</h2><span className="badge">{remote.mode==='live'&&remote.armed?'Live armed':'Preview · no input'}</span></div><p>Run a saved sequence of registered controls, delays and exact display checks. Scripts must first be registered and approved on the DCS computer.</p>
    <div className="workflow-progress" role="status"><strong>{run?`${run.status} · ${run.mode??remote.mode}`:'No workflow running'}</strong>{run&&<><progress max={Math.max(1,run.step_count)} value={Math.max(0,run.step_index)}/><span>Step {Math.min(run.step_index+1,run.step_count)} of {run.step_count} · {run.message}</span>{run.events?.length?<details><summary>Run history</summary><ol>{run.events.map((event,index)=><li key={index}>{event.status} {event.message??event.detail}</li>)}</ol></details>:null}</>}<button disabled={(!remote.active_run&&!busy)||stopping} onClick={onStop}>Stop workflow</button></div>
    <div className="workflow-library">{remote.workflows.map(workflow=><article key={workflow.id}><div><h3>{workflow.name}</h3><p>{workflow.aircraft} · {workflow.steps.length} steps</p></div><button disabled={!enabled||busy||remote.busy||workflow.aircraft!==remote.aircraft} onClick={()=>onRun(workflow.id)}>Run {workflow.name}</button>{remote.can_edit&&<><button disabled={saving} onClick={()=>{setDraft(structuredClone(workflow));setError('');}}>Edit {workflow.name}</button><button disabled={saving||remote.busy} onClick={()=>void remove(workflow)}>Delete {workflow.name}</button></>}</article>)}{!remote.workflows.length&&<p>No saved workflows. Create one on the DCS computer.</p>}</div>
    <h3>Registered mission scripts</h3><p>Single-player mission scripts run once. Stop cancels pending steps; it cannot interrupt Lua already handed to DCS.</p><div className="workflow-library">{remote.scripts.map(script=><article key={script.id}><div><h3>{script.name??script.id}</h3><p>{script.description}</p><p>{script.available?'Ready':script.reason??'Unavailable'} · Single-player only</p>{(script.approved_revision??script.sha256)&&<small className="hash">Approved revision {script.approved_revision??script.sha256}</small>}</div><button disabled={!enabled||busy||remote.busy||script.available!==true} onClick={()=>onScript(script.id)}>Run {script.name??script.id}</button></article>)}{!remote.scripts.length&&<p>No approved mission scripts are registered.</p>}</div>
    {remote.can_edit?<><button onClick={()=>{setDraft({id:`macro-${uuid().slice(0,8)}`,name:'New workflow',aircraft:remote.aircraft??'',steps:[]});setError('');}}>Create workflow</button>{draft&&<form className="workflow-editor" onSubmit={event=>{event.preventDefault();void save();}}><h3>Edit workflow</h3><label>Workflow name<input aria-label="Workflow name" maxLength={80} required value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></label><p>Aircraft: {draft.aircraft}. Up to 32 steps and 90 seconds. This editor saves a definition; it does not run it.</p><ol>{draft.steps.map((step,index)=><li key={index}><div className="workflow-step-heading"><strong>Step {index+1} · {step.type.replace('_',' ')}</strong><button type="button" aria-label={`Move step ${index+1} up`} disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button type="button" aria-label={`Move step ${index+1} down`} disabled={index===draft.steps.length-1} onClick={()=>move(index,1)}>↓</button><button type="button" aria-label={`Remove step ${index+1}`} onClick={()=>setDraft({...draft,steps:draft.steps.filter((_,i)=>i!==index)})}>Remove</button></div>
      {step.type==='action'&&<label>Registered control<select aria-label={`Step ${index+1} action`} value={step.action_id} onChange={event=>patch(index,{...step,action_id:event.target.value})}>{buttons.map(button=><option key={button.id} value={button.id}>{button.name}{button.available?'':` · ${button.reason??'Unavailable'}`}</option>)}</select></label>}
      {step.type==='delay'&&<label>Delay seconds<input aria-label={`Step ${index+1} delay`} type="number" min="0.1" max="5" step="0.1" value={step.seconds} onChange={event=>patch(index,{...step,seconds:Number(event.target.value)})}/></label>}
      {step.type==='wait'&&<><label>Fresh exported field<select aria-label={`Step ${index+1} field`} value={JSON.stringify([step.display_id,step.name])} onChange={event=>{const [display_id,name]=JSON.parse(event.target.value);patch(index,{...step,display_id,name});}}>{!fields.some(field=>field.display_id===step.display_id&&field.name===step.name)&&<option value={JSON.stringify([step.display_id,step.name])}>{step.name||'No fresh fields available'} · unavailable</option>}{fields.map((field,i)=><option key={i} value={JSON.stringify([field.display_id,field.name])}>Display {field.display_id} · {field.name}</option>)}</select></label><label>Equals exact text<input aria-label={`Step ${index+1} expected text`} maxLength={200} value={step.equals} onChange={event=>patch(index,{...step,equals:event.target.value})}/></label><label>Timeout seconds<input type="number" min="1" max="15" value={step.timeout_s} onChange={event=>patch(index,{...step,timeout_s:Number(event.target.value)})}/></label></>}
      {step.type==='mission_script'&&<label>Approved script<select aria-label={`Step ${index+1} script`} value={step.script_id} onChange={event=>patch(index,{...step,script_id:event.target.value})}>{remote.scripts.map(script=><option key={script.id} value={script.id}>{script.name??script.id}</option>)}</select></label>}
    </li>)}</ol><div className="workspace-preset-row"><button type="button" disabled={draft.steps.length>=32||!buttons.length} onClick={()=>add('action')}>Add control</button><button type="button" disabled={draft.steps.length>=32} onClick={()=>add('delay')}>Add delay</button><button type="button" disabled={draft.steps.length>=32||!fields.length} onClick={()=>add('wait')}>Add display check</button><button type="button" disabled={draft.steps.length>=32||!remote.scripts.length} onClick={()=>add('mission_script')}>Add script</button></div><div className="workspace-preset-row"><button type="submit" disabled={saving||!draft.steps.length||!draft.name.trim()}>Save workflow</button><button type="button" onClick={()=>setDraft(undefined)}>Close editor</button></div></form>}</>:<p>Workflow editing is available on your DCS computer. Connect controls and enable live on this screen to run saved workflows in the cockpit.</p>}{error&&<p role="alert">{error}</p>}
  </section>;
}
