import { useRef, useState } from 'react';
import { downloadLayout, panelNames, presetWorkspace, validateWorkspace } from './workspace';
import type { Workspace, PanelSize } from './workspace';
export default function WorkspaceEditor({workspace,onChange,device}:{workspace:Workspace;onChange:(value:Workspace)=>void;device:string}){
  const [error,setError]=useState('');const file=useRef<HTMLInputElement>(null);
  function move(index:number,delta:number){const panels=[...workspace.panels];[panels[index],panels[index+delta]]=[panels[index+delta],panels[index]];onChange({...workspace,panels});}
  async function importFile(selected?:File){setError('');if(!selected)return;try{if(selected.size>32768)throw new Error();const imported=validateWorkspace(JSON.parse(await selected.text()));if(!imported)throw new Error();onChange(imported);}catch{setError('This is not a valid companion layout. Import a layout JSON file under 32 KB; commands, scripts and other data are not accepted.');}if(file.current)file.current.value='';}
  return <details className="panel workspace-editor"><summary>Edit workspace · {device} layout</summary><p>Arrange this aircraft’s panels for this device. Layout changes never send input.</p><div className="workspace-preset-row"><button onClick={()=>onChange({...presetWorkspace('touch'),favourites:workspace.favourites})}>Large touch preset</button><button onClick={()=>onChange({...presetWorkspace('cockpit'),favourites:workspace.favourites})}>Cockpit preset</button><button onClick={()=>onChange(presetWorkspace())}>Reset workspace</button></div><div className="workspace-panel-list">{workspace.panels.map((panel,index)=><div className="workspace-panel-row" key={panel.id}><label><input type="checkbox" checked={panel.visible} onChange={event=>onChange({...workspace,panels:workspace.panels.map(item=>item.id===panel.id?{...item,visible:event.target.checked}:item)})}/>{panelNames[panel.id]}</label><select aria-label={`${panelNames[panel.id]} panel size`} value={panel.size} onChange={event=>onChange({...workspace,panels:workspace.panels.map(item=>item.id===panel.id?{...item,size:event.target.value as PanelSize}:item)})}><option value="compact">Compact</option><option value="regular">Regular</option><option value="large">Large</option></select><select aria-label={`${panelNames[panel.id]} panel style`} value={panel.style} onChange={event=>onChange({...workspace,panels:workspace.panels.map(item=>item.id===panel.id?{...item,style:event.target.value as 'inherit'|'cockpit'|'touch'}:item)})}><option value="inherit">Use global style</option><option value="cockpit">Cockpit</option><option value="touch">Large touch</option></select><button aria-label={`Move ${panelNames[panel.id]} up`} disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button aria-label={`Move ${panelNames[panel.id]} down`} disabled={index===workspace.panels.length-1} onClick={()=>move(index,1)}>↓</button></div>)}</div><div className="workspace-preset-row"><button onClick={()=>downloadLayout(workspace)}>Export layout</button><button onClick={()=>file.current?.click()}>Import layout</button><input ref={file} className="visually-hidden" aria-label="Import workspace JSON" type="file" accept=".json,application/json" onChange={event=>void importFile(event.target.files?.[0])}/></div>{error&&<p role="alert">{error}</p>}</details>;
}
